<?php

/**
 * @file
 * Contains custom_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_migrate module.
    case 'help.page.custom_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Migrate') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_migration_plugins_alter().
 */
function custom_migrate_migration_plugins_alter(&$definitions) {
  $modulePath = drupal_get_path('module', 'custom_migrate');
  $definitions['person_csv']['source']['path'] = $modulePath . $definitions['person_csv']['source']['path'];
  $definitions['person_file_csv']['source']['path'] = $modulePath . $definitions['person_file_csv']['source']['path'];
  $definitions['person_file_csv']['source']['constants']['source_base_path'] = $modulePath . $definitions['person_file_csv']['source']['constants']['source_base_path'];
}
